name: rejoin_dist_change_reward
class: saferl.aerospace.tasks.rejoin.processors.RejoinDistanceChangeRewardProcessor
config:
  rejoin_region: rejoin_region
  rejoin_status: in_rejoin
  reward: -1.0e-05
  wingman: wingman
