env: saferl.aerospace.tasks.docking.task.DockingEnv
env_config:
  agent: deputy
  env_objs:
  - name: deputy
    class: saferl.aerospace.models.cwhspacecraft.platforms.CWHSpacecraft2d
    config:
      controller:
        actuators:
        - name: thrust_x
          space: discrete
          points: 11
          bounds: [-10, 10]
        - name: thrust_y
          space: discrete
          points: 11
          bounds: [-10, 10]
      initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
      init:
        x: [-2000, 2000]
        x_dot: 0
        y: [-2000, 2000]
        y_dot: 0
  - name: chief
    class: saferl.aerospace.models.cwhspacecraft.platforms.CWHSpacecraft2d
    config:
      initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
      init:
        x: 0
        x_dot: 0
        y: 0
        y_dot: 0
  - name: docking_region
    class: saferl.environment.models.geometry.RelativeCircle
    config:
      ref: chief
      x_offset: 0
      y_offset: 0
      radius: 20
      initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
  observation:
  - name: observation_processor
    class: saferl.aerospace.tasks.docking.processors.DockingObservationProcessor
    config:
      deputy: deputy
      mode: 2d
  reward:
  - name: time_reward
    class: saferl.aerospace.tasks.docking.processors.TimeRewardProcessor
    config:
      reward: -0.01
  - name: dist_change_reward
    class: saferl.aerospace.tasks.docking.processors.DistanceChangeRewardProcessor
    config:
      deputy: deputy
      docking_region: docking_region
      reward: -1.0e-03
  - name: failure_reward
    class: saferl.aerospace.tasks.docking.processors.FailureRewardProcessor
    config:
      failure_status: failure
      reward:
        crash: -1
        distance: -1
        timeout: -1
  - name: success_reward
    class: saferl.aerospace.tasks.docking.processors.SuccessRewardProcessor
    config:
      reward: 1
      success_status: success
  status:
  - name: docking_status
    class: saferl.aerospace.tasks.docking.processors.DockingStatusProcessor
    config:
      deputy: deputy
      docking_region: docking_region
  - name: docking_distance
    class: saferl.aerospace.tasks.docking.processors.DockingDistanceStatusProcessor
    config:
      deputy: deputy
      docking_region: docking_region
  - name: failure
    class: saferl.aerospace.tasks.docking.processors.FailureStatusProcessor
    config:
      docking_distance: docking_distance
      max_goal_distance: 40000
      timeout: 1000
  - name: success
    class: saferl.aerospace.tasks.docking.processors.SuccessStatusProcessor
    config:
      docking_status: docking_status
  verbose: false
