auto_wrap_old_gym_envs: false
env: saferl.aerospace.tasks.docking.task.DockingEnv
env_config:
  agent: deputy
  step_size: 1
  env_objs:
  - name: chief
    class: saferl.aerospace.models.cwhspacecraft.platforms.CWHSpacecraft2d
    config:
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
        x: 0
        x_dot: 0
        y: 0
        y_dot: 0
  - name: deputy
    class: saferl.aerospace.models.cwhspacecraft.platforms.CWHSpacecraft2d
    config:
      integration_method: RK45
      controller:
        class: saferl.environment.models.platforms.AgentController
        actuators:
        - name: thrust_x
          space: continuous
          bounds: [-1, 1]
        - name: thrust_y
          space: continuous
          bounds: [-1, 1]
      init:
        initializer: saferl.aerospace.tasks.docking.initializers.ConstrainedDeputyPolarInitializer
        ref: chief
        radius: 5
        angle: [0, 6.283185307179586]
  - name: docking_region
    class: saferl.environment.models.geometry.RelativeCircle
    config:
      ref: chief
      x_offset: 0
      y_offset: 0
      radius: 0.25
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
  status:
    - name: in_docking
      class: saferl.aerospace.tasks.docking.processors.InDockingStatusProcessor
      config:
        deputy: deputy
        docking_region: docking_region
    - name: docking_distance
      class: saferl.aerospace.tasks.docking.processors.DockingDistanceStatusProcessor
      config:
        deputy: deputy
        docking_region: docking_region
    - name: delta_v
      class: saferl.aerospace.tasks.docking.processors.DockingThrustDeltaVStatusProcessor
      config:
        target: deputy
    - name: custom_metrics.delta_v_total
      class: saferl.aerospace.tasks.docking.processors.AccumulatorStatusProcessor
      config:
        status: delta_v
    - name: max_vel_limit
      class: saferl.aerospace.tasks.docking.processors.DockingVelocityLimit
      config:
        target: deputy
        dist_status: docking_distance
        vel_threshold: 0.2
        threshold_dist: 0.5
        slope: 2
    - name: max_vel_violation
      class: saferl.aerospace.tasks.docking.processors.DockingVelocityLimitViolation
      config:
        target: deputy
        ref: chief
        vel_limit_status: max_vel_limit
    - name: max_vel_constraint
      class: saferl.aerospace.tasks.docking.processors.RelativeVelocityConstraint
      config:
        target: deputy
        ref: chief
        vel_limit_status: max_vel_limit
    - name: failure
      class: saferl.aerospace.tasks.docking.processors.FailureStatusProcessor
      config:
        docking_distance: docking_distance
        max_goal_distance: 100
        timeout: 200
        in_docking_status: in_docking
        max_vel_constraint_status: max_vel_constraint
    - name: success
      class: saferl.aerospace.tasks.docking.processors.SuccessStatusProcessor
      config:
        in_docking_status: in_docking
        max_vel_constraint_status: max_vel_constraint
  observation:
    # - name: observation_processor
    #   class: saferl.aerospace.tasks.docking.processors.DockingObservationProcessor
    #   config:
    #     deputy: deputy
    #     mode: 2d
    - name: obs_x
      class: saferl.environment.tasks.processor.observation.AttributeObservationProcessor
      config:
        target: deputy
        attr: x
        observation_space_shape: 1
        normalization: 10
    - name: obs_y
      class: saferl.environment.tasks.processor.observation.AttributeObservationProcessor
      config:
        target: deputy
        attr: y
        observation_space_shape: 1
        normalization: 10
    - name: obs_x_dot
      class: saferl.environment.tasks.processor.observation.AttributeObservationProcessor
      config:
        target: deputy
        attr: x_dot
        observation_space_shape: 1
        normalization: 0.5
    - name: obs_y_dot
      class: saferl.environment.tasks.processor.observation.AttributeObservationProcessor
      config:
        target: deputy
        attr: y_dot
        observation_space_shape: 1
        normalization: 0.5
  reward:
    - name: dist_change_5m_reward
      class: saferl.environment.tasks.processor.reward.DistanceExponentialChangeRewardProcessor
      config:
        agent: deputy
        target: docking_region
        pivot: 5
    - name: dist_change_0.5m_reward
      class: saferl.environment.tasks.processor.reward.DistanceExponentialChangeRewardProcessor
      config:
        agent: deputy
        target: docking_region
        pivot: 0.5
    - name: delta_v
      class: saferl.environment.tasks.processor.reward.ProportionalRewardProcessor
      config:
        scale: -0.01
        bias: 0
        proportion_status: delta_v
    - name: max_vel_constraint
      class: saferl.environment.tasks.processor.reward.ProportionalRewardProcessor
      config:
        scale: -0.01
        bias: -0.01
        proportion_status: max_vel_violation
        cond_status: max_vel_constraint
        cond_status_invert: True
        lower_bound: -5
        lower_bound_terminal: failure
    - name: failure_reward
      class: saferl.aerospace.tasks.docking.processors.FailureRewardProcessor
      config:
        failure_status: failure
        reward:
          crash: -1
          distance: -1
          timeout: -1
          reward_lower_bound_max_vel_constraint: 0
    - name: success_reward
      class: saferl.aerospace.tasks.docking.processors.SuccessRewardProcessor
      config:
        reward: 1
        success_status: success
        timeout: 200
  verbose: false
gamma: 0.968559
lambda: 0.928544
framework: tf
