class: Dubins2dPlatform
config:
  controller:
    actuators:
    - name: rudder
      points: 5
      space: discrete
    - name: throttle
      points: 5
      space: discrete
  init:
    heading: [0, 6.283185307179586]
    v: [10, 100]
    x: [-4000, 4000]
    y: [-4000, 4000]
name: wingman
