name: wingman
class: Dubins2dPlatform
config:
  controller:
    actuators:
      - name: rudder
        space: discrete
        points: 5
      - name: throttle
        space: discrete
        points: 5
  init:
    heading: [0, 6.283185307179586]
    v: [10, 100]
    x: [-4000, 4000]
    y: [-4000, 4000]
