name: lead
class: saferl.aerospace.models.dubins.platforms.Dubins2dPlatform
config:
  init:
    initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
    heading: [0, 6.283185307179586]
    v: [40, 60]
    x: [-4000, 4000]
    y: [-4000, 4000]
