name: wingman
class: saferl.aerospace.models.dubins.platforms.Dubins2dPlatform
config:
  v_min: 10
  v_max: 100
  controller:
    class: saferl.environment.models.platforms.AgentController
    actuators:
      - name: rudder
        space: discrete
        points: 5
      - name: throttle
        space: discrete
        points: 5
  init:
    initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
    heading: [0, 6.283185307179586]
    v: [10, 100]
    x: [-4000, 4000]
    y: [-4000, 4000]
