_fake_gpus: false
action_space: null
actions_in_input_normalized: false
batch_mode: complete_episodes
callbacks: !!python/name:saferl.environment.callbacks.CallbacksCaller ''
clip_actions: false
clip_param: 0.3
clip_rewards: null
collect_metrics_timeout: 180
compress_observations: false
create_env_on_driver: false
custom_eval_function: null
custom_resources_per_worker: {}
eager_tracing: false
entropy_coeff: 0.0
entropy_coeff_schedule: null
env: !!python/name:saferl.aerospace.tasks.docking.task.DockingEnv ''
env_config:
  agent: deputy
  env_objs:
  - class: &id001 !!python/name:saferl.aerospace.models.cwhspacecraft.platforms.cwh.CWHSpacecraft2d ''
    config:
      init:
        initializer: &id002 !!python/name:saferl.environment.tasks.initializers.RandBoundsInitializer ''
        x: 0
        x_dot: 0
        y: 0
        y_dot: 0
    name: chief
  - class: *id001
    config:
      controller:
        actuators:
        - bounds:
          - -1
          - 1
          name: thrust_x
          post_activation: tanh
          space: continuous
        - bounds:
          - -1
          - 1
          name: thrust_y
          post_activation: tanh
          space: continuous
        class: !!python/name:saferl.environment.models.platforms.AgentController ''
      init:
        angle:
        - 0
        - 6.283185307179586
        initializer: !!python/name:saferl.aerospace.tasks.docking.initializers.ConstrainedDeputyPolarInitializer ''
        radius:
        - 100
        - 150
        ref: chief
      integration_method: RK45
    name: deputy
  - class: !!python/name:saferl.environment.models.geometry.RelativeCircle ''
    config:
      init:
        initializer: *id002
      radius: 0.5
      ref: chief
      x_offset: 0
      y_offset: 0
    name: docking_region
  observation:
  - class: &id003 !!python/name:saferl.environment.tasks.processor.observation.AttributeObservationProcessor ''
    config:
      attr: x
      normalization: 100
      observation_space_shape: 1
      target: deputy
    name: obs_x
  - class: *id003
    config:
      attr: y
      normalization: 100
      observation_space_shape: 1
      target: deputy
    name: obs_y
  - class: *id003
    config:
      attr: x_dot
      normalization: 0.5
      observation_space_shape: 1
      target: deputy
    name: obs_x_dot
  - class: *id003
    config:
      attr: y_dot
      normalization: 0.5
      observation_space_shape: 1
      target: deputy
    name: obs_y_dot
  reward:
  - class: !!python/name:saferl.environment.tasks.processor.reward.DistanceExponentialChangeRewardProcessor ''
    config:
      agent: deputy
      pivot: 100
      target: docking_region
    name: dist_change_reward
  - class: &id004 !!python/name:saferl.environment.tasks.processor.reward.ProportionalRewardProcessor ''
    config:
      bias: 0
      proportion_status: delta_v
      scale: -0.01
    name: delta_v
  - class: *id004
    config:
      bias: -0.01
      cond_status: max_vel_constraint
      cond_status_invert: true
      lower_bound: -5
      lower_bound_terminal: failure
      proportion_status: max_vel_violation
      scale: -0.01
    name: max_vel_constraint
  - class: !!python/name:saferl.aerospace.tasks.docking.processors.FailureRewardProcessor ''
    config:
      failure_status: failure
      reward:
        crash: -1
        distance: -1
        reward_lower_bound_max_vel_constraint: 0
        timeout: -1
    name: failure_reward
  - class: !!python/name:saferl.aerospace.tasks.docking.processors.SuccessRewardProcessor ''
    config:
      reward: 1
      success_status: success
      timeout: 2000
    name: success_reward
  status:
  - class: !!python/name:saferl.aerospace.tasks.docking.processors.InDockingStatusProcessor ''
    config:
      deputy: deputy
      docking_region: docking_region
    name: in_docking
  - class: !!python/name:saferl.aerospace.tasks.docking.processors.DockingDistanceStatusProcessor ''
    config:
      deputy: deputy
      docking_region: docking_region
    name: docking_distance
  - class: !!python/name:saferl.aerospace.tasks.docking.processors.DockingThrustDeltaVStatusProcessor ''
    config:
      target: deputy
    name: delta_v
  - class: !!python/name:saferl.aerospace.tasks.docking.processors.AccumulatorStatusProcessor ''
    config:
      status: delta_v
    name: custom_metrics.delta_v_total
  - class: !!python/name:saferl.aerospace.tasks.docking.processors.DockingVelocityLimit ''
    config:
      dist_status: docking_distance
      slope: 2
      target: deputy
      threshold_dist: 0.5
      vel_threshold: 0.2
    name: max_vel_limit
  - class: !!python/name:saferl.aerospace.tasks.docking.processors.DockingVelocityLimitViolation ''
    config:
      ref: chief
      target: deputy
      vel_limit_status: max_vel_limit
    name: max_vel_violation
  - class: !!python/name:saferl.aerospace.tasks.docking.processors.RelativeVelocityConstraint ''
    config:
      ref: chief
      target: deputy
      vel_limit_status: max_vel_limit
    name: max_vel_constraint
  - class: !!python/name:saferl.aerospace.tasks.docking.processors.FailureStatusProcessor ''
    config:
      docking_distance: docking_distance
      in_docking_status: in_docking
      max_goal_distance: 40000
      max_vel_constraint_status: max_vel_constraint
      timeout: 2000
    name: failure
  - class: !!python/name:saferl.aerospace.tasks.docking.processors.SuccessStatusProcessor ''
    config:
      in_docking_status: in_docking
      max_vel_constraint_status: max_vel_constraint
    name: success
  step_size: 1
  verbose: false
env_task_fn: null
evaluation_config: {}
evaluation_interval: null
evaluation_num_episodes: 10
evaluation_num_workers: 0
evaluation_parallel_to_training: false
exploration_config:
  type: StochasticSampling
explore: true
extra_python_environs_for_driver: {}
extra_python_environs_for_worker: {}
fake_sampler: false
framework: tf
gamma: 0.968559
grad_clip: null
horizon: null
ignore_worker_failures: false
in_evaluation: false
input: sampler
input_config: {}
input_evaluation:
- is
- wis
kl_coeff: 0.2
kl_target: 0.01
lambda: 0.928544
local_tf_session_args:
  inter_op_parallelism_threads: 8
  intra_op_parallelism_threads: 8
log_level: WARN
log_sys_usage: true
logger_config: null
lr: 5.0e-05
lr_schedule: null
metrics_smoothing_episodes: 100
min_iter_time_s: 0
model:
  _time_major: false
  _use_default_native_models: false
  attention_dim: 64
  attention_head_dim: 32
  attention_init_gru_gate_bias: 2.0
  attention_memory_inference: 50
  attention_memory_training: 50
  attention_num_heads: 1
  attention_num_transformer_units: 1
  attention_position_wise_mlp_dim: 32
  attention_use_n_prev_actions: 0
  attention_use_n_prev_rewards: 0
  conv_activation: relu
  conv_filters: null
  custom_action_dist: null
  custom_model: null
  custom_model_config: {}
  custom_preprocessor: null
  dim: 84
  fcnet_activation: tanh
  fcnet_hiddens:
  - 256
  - 256
  framestack: true
  free_log_std: false
  grayscale: false
  lstm_cell_size: 256
  lstm_use_prev_action: false
  lstm_use_prev_action_reward: -1
  lstm_use_prev_reward: false
  max_seq_len: 20
  no_final_linear: false
  num_framestacks: auto
  post_fcnet_activation: relu
  post_fcnet_hiddens: []
  use_attention: false
  use_lstm: false
  vf_share_layers: false
  zero_mean: true
monitor: -1
multiagent:
  count_steps_by: env_steps
  observation_fn: null
  policies: {}
  policies_to_train: null
  policy_mapping_fn: null
  replay_mode: independent
no_done_at_end: false
normalize_actions: true
num_cpus_for_driver: 1
num_cpus_per_worker: 1
num_envs_per_worker: 1
num_gpus: 0
num_gpus_per_worker: 0
num_sgd_iter: 30
num_workers: 6
observation_filter: NoFilter
observation_space: null
optimizer: {}
output: null
output_compress_columns:
- obs
- new_obs
output_max_file_size: 67108864
placement_strategy: PACK
postprocess_inputs: false
preprocessor_pref: deepmind
record_env: false
remote_env_batch_wait_ms: 0
remote_worker_envs: false
render_env: false
rollout_fragment_length: 200
sample_async: false
sample_collector: !!python/name:ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector ''
seed: 0
sgd_minibatch_size: 128
shuffle_buffer_size: 0
shuffle_sequences: true
simple_optimizer: -1
soft_horizon: false
synchronize_filters: true
tf_session_args:
  allow_soft_placement: true
  device_count:
    CPU: 1
  gpu_options:
    allow_growth: true
  inter_op_parallelism_threads: 2
  intra_op_parallelism_threads: 2
  log_device_placement: false
timesteps_per_iteration: 0
train_batch_size: 4000
use_critic: true
use_gae: true
vf_clip_param: 10.0
vf_loss_coeff: 1.0
vf_share_layers: -1
