env: saferl.aerospace.tasks.rejoin.task.DubinsRejoin
env_config:
  agent: wingman
  step_size: 1
  env_objs:
  - name: lead
    class: saferl.aerospace.models.dubins.platforms.Dubins2dPlatform
    config:
      v_min: 200
      v_max: 400
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
        heading: 0.76
        v: 250
        x: 0
        y: 0
  - name: wingman
    class: saferl.aerospace.models.dubins.platforms.Dubins2dPlatform
    config:
      v_min: 200
      v_max: 400
      integration_method: RK45
      controller:
        class: saferl.environment.models.platforms.AgentController
        actuators:
        - name: rudder
          space: continuous
          rescale: true
          bounds: [-0.174533, 0.174533]
        - name: throttle
          space: continuous
          rescale: true
          bounds: [-96.5, 96.5]
      init:
        initializer: saferl.aerospace.tasks.rejoin.initializers.WingmanPolarInitializer
        heading: -1.51
        v: 350
        ref: lead
        radius: 5000
        angle: -0.35
  - name: rejoin_region
    class: saferl.environment.models.geometry.RelativeCircle
    config:
      ref: lead
      aspect_angle: 60
      r_offset: 500
      radius: 150
      track_orientation: true
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
  observation:
  - name: observation_processor
    class: saferl.aerospace.tasks.rejoin.processors.DubinsObservationProcessor
    config:
      lead: lead
      mode: magnorm
      reference: wingman
      rejoin_region: rejoin_region
      wingman: wingman
  reward:
  - name: rejoin_reward
    class: saferl.aerospace.tasks.rejoin.processors.RejoinRewardProcessor
    config:
      rejoin_prev_status: in_rejoin_prev
      rejoin_status: in_rejoin
      reward: 0.1
  - name: rejoin_first_time_reward
    class: saferl.aerospace.tasks.rejoin.processors.RejoinFirstTimeRewardProcessor
    config:
      rejoin_status: in_rejoin
      reward: 0.25
  - name: rejoin_dist_change_reward
    class: saferl.environment.tasks.processor.reward.DistanceExponentialChangeRewardProcessor
    config:
      agent: wingman
      target: rejoin_region
      pivot: 5000
  - name: failure_reward
    class: saferl.aerospace.tasks.docking.processors.FailureRewardProcessor
    config:
      failure_status: failure
      reward:
        crash: -1
        distance: -1
        timeout: -1
  - name: success_reward
    class: saferl.aerospace.tasks.docking.processors.SuccessRewardProcessor
    config:
      reward: 1
      success_status: success
      timeout: 1000
  status:
  - name: in_rejoin
    class: saferl.aerospace.tasks.rejoin.processors.DubinsInRejoin
    config:
      rejoin_region: rejoin_region
      wingman: wingman
  - name: in_rejoin_prev
    class: saferl.aerospace.tasks.rejoin.processors.DubinsInRejoinPrev
    config:
      rejoin_status: in_rejoin
  - name: rejoin_time
    class: saferl.aerospace.tasks.rejoin.processors.DubinsRejoinTime
    config:
      rejoin_status: in_rejoin
  - name: time_elapsed
    class: saferl.aerospace.tasks.rejoin.processors.DubinsTimeElapsed
    config: {}
  - name: lead_distance
    class: saferl.aerospace.tasks.rejoin.processors.DubinsLeadDistance
    config:
      lead: lead
      wingman: wingman
  - name: failure
    class: saferl.aerospace.tasks.rejoin.processors.DubinsFailureStatus
    config:
      lead_distance: lead_distance
      max_goal_distance: 40000
      safety_margin:
        aircraft: 100
      time_elapsed: time_elapsed
      timeout: 1000
  - name: success
    class: saferl.aerospace.tasks.rejoin.processors.DubinsSuccessStatus
    config:
      rejoin_time: rejoin_time
      success_time: 20
  verbose: false
