env: saferl.aerospace.tasks.rejoin.task.DubinsRejoin
env_config:
  agent: wingman
  step_size: 1
  env_objs:
  - name: lead
    class: saferl.aerospace.models.dubins.platforms.Dubins2dPlatform
    config:
      v_min: 200
      v_max: 400
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
        heading: [0, 6.283185307179586]
        v: [250, 250]
        x: [-4000, 4000]
        y: [-4000, 4000]
  - name: wingman
    class: saferl.aerospace.models.dubins.platforms.Dubins2dPlatform
    config:
      v_min: 200
      v_max: 400
      controller:
        class: saferl.environment.models.platforms.AgentController
        actuators:
        - name: rudder
          space: discrete
          bounds: [-0.1745329, 0.1745329]
          points: 5
        - name: throttle
          space: discrete
          bounds: [-96.5, 96.5]
          points: 5
      init:
        initializer: saferl.aerospace.tasks.rejoin.initializers.WingmanPolarInitializer
        heading: [0, 6.283185307179586]
        v: [200, 400]
        x: [-4000, 4000]
        y: [-4000, 4000]

  - name: rejoin_region
    class: saferl.environment.models.geometry.RelativeCircle
    config:
      ref: lead
      aspect_angle: 60
      r_offset: 500
      radius: 150
      track_orientation: true
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
  observation:
  - name: observation_processor
    class: saferl.aerospace.tasks.rejoin.processors.DubinsObservationProcessor
    config:
      lead: lead
      mode: magnorm
      reference: wingman
      rejoin_region: rejoin_region
      wingman: wingman
  reward:
  - name: rejoin_reward
    class: saferl.aerospace.tasks.rejoin.processors.RejoinRewardProcessor
    config:
      rejoin_prev_status: in_rejoin_prev
      rejoin_status: in_rejoin
      reward: 0.1
  - name: rejoin_first_time_reward
    class: saferl.aerospace.tasks.rejoin.processors.RejoinFirstTimeRewardProcessor
    config:
      rejoin_status: in_rejoin
      reward: 0.25
  - name: time_reward
    class: saferl.aerospace.tasks.docking.processors.TimeRewardProcessor
    config:
      reward: -0.01
  - name: rejoin_dist_change_reward
    class: saferl.aerospace.tasks.rejoin.processors.RejoinDistanceChangeRewardProcessor
    config:
      rejoin_region: rejoin_region
      rejoin_status: in_rejoin
      reward: -1.0e-05
      wingman: wingman
  - name: failure_reward
    class: saferl.aerospace.tasks.docking.processors.FailureRewardProcessor
    config:
      failure_status: failure
      reward:
        crash: -1
        distance: -1
        timeout: -1
  - name: success_reward
    class: saferl.aerospace.tasks.docking.processors.SuccessRewardProcessor
    config:
      reward: 1
      success_status: success
  status:
  - name: in_rejoin
    class: saferl.aerospace.tasks.rejoin.processors.DubinsInRejoin
    config:
      rejoin_region: rejoin_region
      wingman: wingman
  - name: in_rejoin_prev
    class: saferl.aerospace.tasks.rejoin.processors.DubinsInRejoinPrev
    config:
      rejoin_status: in_rejoin
  - name: rejoin_time
    class: saferl.aerospace.tasks.rejoin.processors.DubinsRejoinTime
    config:
      rejoin_status: in_rejoin
  - name: time_elapsed
    class: saferl.aerospace.tasks.rejoin.processors.DubinsTimeElapsed
    config: {}
  - name: lead_distance
    class: saferl.aerospace.tasks.rejoin.processors.DubinsLeadDistance
    config:
      lead: lead
      wingman: wingman
  - name: failure
    class: saferl.aerospace.tasks.rejoin.processors.DubinsFailureStatus
    config:
      lead_distance: lead_distance
      max_goal_distance: 40000
      safety_margin:
        aircraft: 100
      time_elapsed: time_elapsed
      timeout: 1000
  - name: success
    class: saferl.aerospace.tasks.rejoin.processors.DubinsSuccessStatus
    config:
      rejoin_time: rejoin_time
      success_time: 20
  verbose: false
