env: saferl.aerospace.tasks.rejoin.task.DubinsRejoin
env_config:
  agent: wingman
  step_size: 1
  env_objs:
  - name: lead
    class: saferl.aerospace.models.dubins.platforms.Dubins3dPlatform
    config:
      v_min: 200
      v_max: 400
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
        heading: [0, 6.283185307179586]
        v: [250, 300]
        x: [5000, 10000]
        y: [5000, 10000]
        z: [12000, 14000]
  - name: wingman
    class: saferl.aerospace.models.dubins.platforms.Dubins3dPlatform
    config:
      v_min: 200
      v_max: 400
      integration_method: RK45
      controller:
        class: saferl.environment.models.platforms.AgentController
        actuators:
        - name: ailerons
          space: continuous
          points: 5
          bounds: [-0.17, 0.17]
        - name: elevator
          space: continuous
          points: 5
          bounds: [-0.09, 0.09]
        - name: throttle
          space: continuous
          bounds: [-96.5, 96.5]
          points: 5
      init:
        initializer: saferl.aerospace.tasks.rejoin.initializers.WingmanPolarInitializer
        ref: lead
        heading: [0, 6.283185307179586]
        v: [200, 400]
        radius: [5000, 10000]
        angle: [0, 6.283185307179586]
        z: [10000, 16000]
  - name: rejoin_region
    class: saferl.environment.models.geometry.RelativeCylinder
    config:
      ref: lead
      aspect_angle: 60
      r_offset: 500
      radius: 100
      height: 300
      track_orientation: true
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
  observation:
  - name: observation_processor
    class: saferl.aerospace.tasks.rejoin.processors.Dubins3dObservationProcessor
    config:
      lead: lead
      mode: magnorm
      reference: wingman
      rejoin_region: rejoin_region
      wingman: wingman
  reward:
  - name: rejoin_reward
    class: saferl.aerospace.tasks.rejoin.processors.RejoinRewardProcessor
    config:
      rejoin_prev_status: in_rejoin_prev
      rejoin_status: in_rejoin
      reward: 0.1
      refund: False
  - name: rejoin_first_time_reward
    class: saferl.aerospace.tasks.rejoin.processors.RejoinFirstTimeRewardProcessor
    config:
      rejoin_status: in_rejoin
      reward: 0.25
  - name: rejoin_dist_change_reward
    class: saferl.environment.tasks.processor.reward.DistanceExponentialChangeRewardProcessor
    config:
      agent: wingman
      target: rejoin_region
      pivot: 5000
  - name: failure_reward
    class: saferl.aerospace.tasks.docking.processors.FailureRewardProcessor
    config:
      failure_status: failure
      reward:
        crash: -1
        distance: -1
        timeout: -1
        leave_rejoin: 0
  - name: success_reward
    class: saferl.aerospace.tasks.docking.processors.SuccessRewardProcessor
    config:
      reward: 1
      success_status: success
      timeout: 2000
  status:
  - name: in_rejoin
    class: saferl.aerospace.tasks.rejoin.processors.DubinsInRejoin
    config:
      rejoin_region: rejoin_region
      wingman: wingman
  - name: in_rejoin_prev
    class: saferl.aerospace.tasks.rejoin.processors.DubinsInRejoinPrev
    config:
      rejoin_status: in_rejoin
  - name: rejoin_time
    class: saferl.aerospace.tasks.rejoin.processors.DubinsRejoinTime
    config:
      rejoin_status: in_rejoin
  - name: time_elapsed
    class: saferl.aerospace.tasks.rejoin.processors.DubinsTimeElapsed
    config: {}
  - name: lead_distance
    class: saferl.aerospace.tasks.rejoin.processors.DubinsLeadDistance
    config:
      lead: lead
      wingman: wingman
  - name: failure
    class: saferl.aerospace.tasks.rejoin.processors.DubinsFailureStatus
    config:
      lead_distance: lead_distance
      max_goal_distance: 100000
      safety_margin:
        aircraft: 100
      time_elapsed: time_elapsed
      timeout: 2000
      on_leave_rejoin: True
  - name: success
    class: saferl.aerospace.tasks.rejoin.processors.DubinsSuccessStatus
    config:
      rejoin_time: rejoin_time
      success_time: 20
  verbose: false
