env: saferl.aerospace.tasks.docking.task.DockingEnv
env_config:
  agent: deputy
  step_size: 1
  env_objs:
  - name: chief
    class: saferl.aerospace.models.docking_1d.platforms.Spacecraft1D
    config:
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
        x: 0
        x_dot: 0
  - name: deputy
    class: saferl.aerospace.models.docking_1d.platforms.Spacecraft1D
    config:
      integration_method: RK45
      controller:
        class: saferl.environment.models.platforms.AgentController
        actuators:
        - name: thrust_x
          space: continuous
          bounds: [-1, 1]
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
        x: 100
        x_dot: 0
  - name: docking_region
    class: saferl.environment.models.geometry.RelativeCircle
    config:
      ref: chief
      x_offset: 0
      y_offset: 0
      radius: 0.5
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
  status:
    - name: in_docking
      class: saferl.aerospace.tasks.docking.processors.InDockingStatusProcessor
      config:
        deputy: deputy
        docking_region: docking_region
    - name: docking_distance
      class: saferl.aerospace.tasks.docking.processors.DockingDistanceStatusProcessor
      config:
        deputy: deputy
        docking_region: docking_region
    - name: failure
      class: saferl.aerospace.models.docking_1d.platforms.Docking1dFailureStatusProcessor
      config:
        docking_distance: docking_distance
        max_goal_distance: 40000
        timeout: 2000
        in_docking_status: in_docking
    - name: success
      class: saferl.aerospace.models.docking_1d.platforms.Docking1dSuccessStatusProcessor
      config:
        in_docking_status: in_docking
  observation:
    - name: observation_processor
      class: saferl.aerospace.models.docking_1d.platforms.Docking1dObservationProcessor
      config:
        deputy: deputy
  reward:
    - name: dist_change_reward
      class: saferl.environment.tasks.processor.reward.DistanceExponentialChangeRewardProcessor
      config:
        agent: deputy
        target: docking_region
        pivot: 100
    - name: failure_reward
      class: saferl.aerospace.tasks.docking.processors.FailureRewardProcessor
      config:
        failure_status: failure
        reward:
          crash: -1
          distance: -1
          timeout: -1
          reward_lower_bound_max_vel_constraint: 0
    - name: success_reward
      class: saferl.aerospace.tasks.docking.processors.SuccessRewardProcessor
      config:
        reward: 1
        success_status: success
        timeout: 2000
  verbose: false
gamma: 0.968559
lambda: 0.928544
