name: deputy
class: CWHSpacecraft2d
config:
  controller:
    actuators:
      - name: thrust_x
        space: discrete
        points: 11
        bounds: [-10, 10]
      - name: thrust_y
        space: discrete
        points: 11
        bounds: [-10, 10]
  init:
    x: [-2000, 2000]
    x_dot: 0
    y: [-2000, 2000]
    y_dot: 0
