class: CWHSpacecraft2d
config:
  controller:
    actuators:
    - bounds: [-10, 10]
      name: thrust_x
      points: 11
      space: discrete
    - bounds: [-10, 10]
      name: thrust_y
      points: 11
      space: discrete
  init:
    x: [-2000, 2000]
    x_dot: 0
    y: [-2000, 2000]
    y_dot: 0
name: deputy