name: observation_processor
class: saferl.aerospace.tasks.rejoin.processors.DubinsObservationProcessor
config:
  lead: lead
  mode: magnorm
  reference: wingman
  rejoin_region: rejoin_region
  wingman: wingman
