env: DockingEnv
env_config:
  agent: deputy
  env_objs:
  - name: deputy
    class: CWHSpacecraft2d
    config:
      controller:
        actuators:
        - name: thrust_x
          space: discrete
          points: 11
          bounds: [-10, 10]
        - name: thrust_y
          space: discrete
          points: 11
          bounds: [-10, 10]
      init:
        x: [-2000, 2000]
        x_dot: 0
        y: [-2000, 2000]
        y_dot: 0
  - name: chief
    class: CWHSpacecraft2d
    config:
      init:
        x: 0
        x_dot: 0
        y: 0
        y_dot: 0
  - name: docking_region
    class: RelativeCircle
    config:
      ref: chief
      x_offset: 0
      y_offset: 0
      radius: 20
  observation:
  - name: observation_processor
    class: DockingObservationProcessor
    config:
      deputy: deputy
      mode: 2d
  reward:
  - name: time_reward
    class: TimeRewardProcessor
    config:
      reward: -0.01
  - name: dist_change_reward
    class: DistanceChangeRewardProcessor
    config:
      deputy: deputy
      docking_region: docking_region
      reward: -1.0e-05
  - name: failure_reward
    class: FailureRewardProcessor
    config:
      failure_status: failure
      reward:
        crash: -1
        distance: -1
        timeout: -1
  - name: success_reward
    class: SuccessRewardProcessor
    config:
      reward: 1
      success_status: success
  status:
  - name: docking_status
    class: DockingStatusProcessor
    config:
      deputy: deputy
      docking_region: docking_region
  - name: docking_distance
    class: DockingDistanceStatusProcessor
    config:
      deputy: deputy
      docking_region: docking_region
  - name: failure
    class: FailureStatusProcessor
    config:
      docking_distance: docking_distance
      max_goal_distance: 40000
      timeout: 1000
  - name: success
    class: SuccessStatusProcessor
    config:
      docking_status: docking_status
  verbose: false
