env: DockingEnv
env_config:
  agent: deputy
  env_objs:
  - class: CWHSpacecraft2d
    config:
      controller:
        actuators:
        - bounds: [-10, 10]
          name: thrust_x
          points: 11
          space: discrete
        - bounds: [-10, 10]
          name: thrust_y
          points: 11
          space: discrete
      init:
        x: [-2000, 2000]
        x_dot: 0
        y: [-2000, 2000]
        y_dot: 0
    name: deputy
  - class: CWHSpacecraft2d
    config:
      init:
        x: 0
        x_dot: 0
        y: 0
        y_dot: 0
    name: chief
  - class: RelativeCircle
    config:
      radius: 20
      ref: chief
      x_offset: 0
      y_offset: 0
    name: docking_region
  observation:
  - class: DockingObservationProcessor
    config:
      deputy: deputy
      mode: 2d
    name: observation_processor
  reward:
  - class: TimeRewardProcessor
    config:
      reward: -0.01
    name: time_reward
  - class: DistanceChangeRewardProcessor
    config:
      deputy: deputy
      docking_region: docking_region
      reward: -1.0e-05
    name: dist_change_reward
  - class: FailureRewardProcessor
    config:
      failure_status: failure
      reward:
        crash: -1
        distance: -1
        timeout: -1
    name: failure_reward
  - class: SuccessRewardProcessor
    config:
      reward: 1
      success_status: success
    name: success_reward
  status:
  - class: DockingStatusProcessor
    config:
      deputy: deputy
      docking_region: docking_region
    name: docking_status
  - class: DockingDistanceStatusProcessor
    config:
      deputy: deputy
      docking_region: docking_region
    name: docking_distance
  - class: FailureStatusProcessor
    config:
      docking_distance: docking_distance
      max_goal_distance: 40000
      timeout: 1000
    name: failure
  - class: SuccessStatusProcessor
    config:
      docking_status: docking_status
    name: success
  verbose: false
