env: saferl.aerospace.tasks.docking.task.DockingEnv
env_config:
  agent: deputy
  step_size: 1
  env_objs:
  - name: chief
    class: saferl.aerospace.models.cwhspacecraft.platforms.CWHSpacecraft2d
    config:
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
        x: 0
        x_dot: 0
        y: 0
        y_dot: 0
  - name: deputy
    class: saferl.aerospace.models.cwhspacecraft.platforms.CWHSpacecraft2d
    config:
      controller:
        class: saferl.environment.models.platforms.AgentController
        actuators:
        - name: thrust_x
          space: discrete
          points: 11
          bounds: [-1, 1]
        - name: thrust_y
          space: discrete
          points: 11
          bounds: [-1, 1]
      init:
        initializer: saferl.aerospace.tasks.docking.initializers.ConstrainedDeputyPolarInitializer
        ref: chief
        radius: [400, 600]
        angle: [0, 6.283185307179586]
  - name: docking_region
    class: saferl.environment.models.geometry.RelativeCircle
    config:
      ref: chief
      x_offset: 0
      y_offset: 0
      radius: 5
      init:
        initializer: saferl.environment.tasks.initializers.RandBoundsInitializer
  status:
    - name: in_docking
      class: saferl.aerospace.tasks.docking.processors.InDockingStatusProcessor
      config:
        deputy: deputy
        docking_region: docking_region
    - name: docking_distance
      class: saferl.aerospace.tasks.docking.processors.DockingDistanceStatusProcessor
      config:
        deputy: deputy
        docking_region: docking_region
    - name: delta_v
      class: saferl.aerospace.tasks.docking.processors.DockingThrustDeltaVStatusProcessor
      config:
        target: deputy
    - name: custom_metrics.delta_v_total
      class: saferl.aerospace.tasks.docking.processors.AccumulatorStatusProcessor
      config:
        status: delta_v
    - name: max_vel_limit
      class: saferl.aerospace.tasks.docking.processors.DockingVelocityLimit
      config:
        target: deputy
        dist_status: docking_distance
        vel_threshold: 0.2
        threshold_dist: 5
        slope: 2
    - name: max_vel_violation
      class: saferl.aerospace.tasks.docking.processors.DockingVelocityLimitViolation
      config:
        target: deputy
        ref: chief
        vel_limit_status: max_vel_limit
    - name: max_vel_constraint
      class: saferl.aerospace.tasks.docking.processors.RelativeVelocityConstraint
      config:
        target: deputy
        ref: chief
        vel_limit_status: max_vel_limit
    - name: failure
      class: saferl.aerospace.tasks.docking.processors.FailureStatusProcessor
      config:
        docking_distance: docking_distance
        max_goal_distance: 40000
        timeout: 3000
        in_docking_status: in_docking
        max_vel_constraint_status: max_vel_constraint
    - name: success
      class: saferl.aerospace.tasks.docking.processors.SuccessStatusProcessor
      config:
        in_docking_status: in_docking
        max_vel_constraint_status: max_vel_constraint
  observation:
    - name: observation_processor
      class: saferl.aerospace.tasks.docking.processors.DockingObservationProcessor
      config:
        deputy: deputy
        mode: 2d
  reward:
    - name: time_reward
      class: saferl.aerospace.tasks.docking.processors.TimeRewardProcessor
      config:
        reward: -0.01
    - name: dist_change_reward
      class: saferl.aerospace.tasks.docking.processors.DistanceChangeRewardProcessor
      config:
        deputy: deputy
        docking_region: docking_region
        reward: -1.0e-03
    - name: delta_v
      class: saferl.environment.tasks.processor.reward.ProportionalRewardProcessor
      config:
        scale: -0.001
        bias: 0
        proportion_status: delta_v
    - name: max_vel_constraint
      class: saferl.environment.tasks.processor.reward.ProportionalRewardProcessor
      config:
        scale: -0.001
        bias: -0.01
        proportion_status: max_vel_violation
        cond_status: max_vel_constraint
        cond_status_invert: True
    - name: failure_reward
      class: saferl.aerospace.tasks.docking.processors.FailureRewardProcessor
      config:
        failure_status: failure
        reward:
          crash: -1
          distance: -1
          timeout: -1
    - name: success_reward
      class: saferl.aerospace.tasks.docking.processors.SuccessRewardProcessor
      config:
        reward: 1
        success_status: success
  verbose: false